// Define the repository information in these attributes
:repository-owner: jaksg82
:repository-name: epeverController

= Epever Solar Charge Controller Monitor Library =

image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml/badge.svg["Check Arduino status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml/badge.svg["Compile Examples status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml/badge.svg["Spell Check status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml"]

This library is based on the sketch https://github.com/glitterkitty/EpEverSolarMonitor. 
This library take all the decoding code inside an external library to simplify and declutter the main sketch.

This code is developed and tested with:

* Arduino MKRWAN 1310
* Arduino MKR485 Shield
* Epever Tracer 5415AN

Using Arduino Libraries:

* https://github.com/arduino-libraries/ArduinoModbus/[ArduinoModbus]
* https://github.com/arduino-libraries/ArduinoRS485/[ArduinoRS485]

== Useful resources ==

* https://github.com/glitterkitty/EpEverSolarMonitor
* https://www.eevblog.com/forum/projects/nodemcu-esp8266-rs485-epever-solar-monitor-diy/
* https://www.arduino.cc/en/ArduinoModbus/ArduinoModbus
* https://en.wikipedia.org/wiki/Modbus[Modbus - Wikipedia]
* http://www.modbus.org/faq.php[Modbus FAQ]

== License ==

Copyright (c) 2022 Simone Giacomoni

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
