- name: arduino/arduino-lint-action
  uses: arduino/arduino-lint-action@v1.0.2

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: submit
          compliance: strict