# This is a basic workflow to help you get started with Actions

name: CompileExamples

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: ${{ matrix.board.fqbn }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:samd:mkrzero
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkr1000
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkrwifi1010
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkrfox1200
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkrwan1300
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkrwan1310
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkrgsm1400
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkrnb1500
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkrvidor4000
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:nano_33_iot
            platforms: |
              - name: arduino:samd

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          libraries: |
            # Install the library from the local path.
            - source-path: ./
            # Additional library dependencies can be listed here.
            # See: https://github.com/arduino/compile-sketches#libraries
            - name: ArduinoRS485
            - name: ArduinoModbus
          sketch-paths: |
            - examples
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: ${{ env.SKETCHES_REPORTS_PATH }}
